// Built-in Word Database
const BUILTIN_WORDS = [
  {
    word: "abandon", phonetic: "/əˈbændən/", pos: "v.",
    roots: "a-(离开 away) + ban(禁令 ban) + don(给予 give) → 把东西给出去不要了",
    defEn: "to give up completely; to leave permanently",
    defZh: "放弃；遗弃；抛弃",
    mnemonic: "谐音'额班等' → 我(额)在班上等不了了 → 放弃不等了",
    exampleEn: "She abandoned her career to travel the world.",
    exampleZh: "她放弃了事业去环游世界。",
    synonyms: ["desert", "forsake", "relinquish"],
    antonyms: ["keep", "maintain", "retain"],
    tags: ["CET4"], difficulty: 2
  },
  {
    word: "accumulate", phonetic: "/əˈkjuːmjəleɪt/", pos: "v.",
    roots: "ac-(加强) + cumul(堆积 heap) + ate(动词后缀) → 不断堆积",
    defEn: "to gather together or acquire an increasing amount",
    defZh: "积累；积聚；堆积",
    mnemonic: "ac+cumulate → 一点一点cumulate(堆积)起来",
    exampleEn: "He accumulated a fortune over the years.",
    exampleZh: "他多年来积累了一笔财富。",
    synonyms: ["gather", "collect", "amass"],
    antonyms: ["disperse", "scatter", "dissipate"],
    tags: ["CET4"], difficulty: 2
  },
  {
    word: "acknowledge", phonetic: "/əkˈnɒlɪdʒ/", pos: "v.",
    roots: "ac-(加强) + knowledge(知识/知道) → 承认知道",
    defEn: "to accept or admit the existence or truth of",
    defZh: "承认；确认；致谢",
    mnemonic: "ac(一个)+knowledge(知识) → 承认一个知识是对的",
    exampleEn: "He acknowledged his mistake immediately.",
    exampleZh: "他立即承认了自己的错误。",
    synonyms: ["admit", "recognize", "concede"],
    antonyms: ["deny", "reject", "ignore"],
    tags: ["CET4"], difficulty: 2
  },
  {
    word: "ambiguous", phonetic: "/æmˈbɪɡjuəs/", pos: "adj.",
    roots: "ambi-(两边 both) + gu(驱动 drive) + ous → 被两边驱动 → 模棱两可",
    defEn: "open to more than one interpretation; unclear",
    defZh: "模棱两可的；含糊不清的",
    mnemonic: "ambi(两边)+gu(咕) → 两边都咕咕叫，分不清哪边",
    exampleEn: "His reply was deliberately ambiguous.",
    exampleZh: "他的回答故意含糊不清。",
    synonyms: ["vague", "unclear", "equivocal"],
    antonyms: ["clear", "definite", "unambiguous"],
    tags: ["CET6", "GRE"], difficulty: 3
  },
  {
    word: "benevolent", phonetic: "/bəˈnevələnt/", pos: "adj.",
    roots: "bene-(好 good/well) + vol(意愿 wish) + ent → 好意愿的",
    defEn: "well-meaning and kindly; charitable",
    defZh: "仁慈的；慈善的；善意的",
    mnemonic: "bene(好)+vol(意愿)+ent → 充满善意的 → 仁慈的",
    exampleEn: "A benevolent smile spread across her face.",
    exampleZh: "一个慈祥的微笑浮现在她脸上。",
    synonyms: ["kind", "charitable", "compassionate"],
    antonyms: ["malevolent", "cruel", "unkind"],
    tags: ["GRE", "TOEFL"], difficulty: 4
  },
  {
    word: "comprehensive", phonetic: "/ˌkɒmprɪˈhensɪv/", pos: "adj.",
    roots: "com-(共同) + prehens(抓住 grasp) + ive → 全部抓住的 → 全面的",
    defEn: "including all or nearly all elements; thorough",
    defZh: "全面的；综合的；详尽的",
    mnemonic: "com(全部)+prehens(抓住) → 把所有东西都抓住 → 全面的",
    exampleEn: "We need a comprehensive review of the policy.",
    exampleZh: "我们需要对该政策进行全面审查。",
    synonyms: ["thorough", "complete", "exhaustive"],
    antonyms: ["partial", "incomplete", "limited"],
    tags: ["CET4"], difficulty: 2
  },
  {
    word: "contemplate", phonetic: "/ˈkɒntəmpleɪt/", pos: "v.",
    roots: "con-(共同/加强) + templ(庙宇 temple) + ate → 在庙里沉思",
    defEn: "to think about deeply; to consider carefully",
    defZh: "沉思；深思；凝视",
    mnemonic: "con+temple+ate → 在寺庙(temple)里吃(ate)东西时沉思",
    exampleEn: "She contemplated her future carefully.",
    exampleZh: "她仔细思考了自己的未来。",
    synonyms: ["ponder", "meditate", "reflect"],
    antonyms: ["ignore", "disregard", "neglect"],
    tags: ["CET6"], difficulty: 3
  },
  {
    word: "deliberate", phonetic: "/dɪˈlɪbərət/", pos: "adj./v.",
    roots: "de-(加强) + liber(称量 weigh) + ate → 反复称量 → 深思熟虑的",
    defEn: "done consciously and intentionally; to think carefully",
    defZh: "故意的；深思熟虑的；仔细考虑",
    mnemonic: "de+liber(自由)+ate → 自由地深思 → 深思熟虑",
    exampleEn: "It was a deliberate attempt to mislead.",
    exampleZh: "这是一次蓄意误导的企图。",
    synonyms: ["intentional", "calculated", "planned"],
    antonyms: ["accidental", "unintentional", "hasty"],
    tags: ["CET6"], difficulty: 3
  },
  {
    word: "deteriorate", phonetic: "/dɪˈtɪəriəreɪt/", pos: "v.",
    roots: "de-(向下) + terior(更坏 worse) + ate → 变得更坏",
    defEn: "to become progressively worse",
    defZh: "恶化；变坏；退化",
    mnemonic: "de(下)+terior(更差) → 向下变差 → 恶化",
    exampleEn: "His health continued to deteriorate.",
    exampleZh: "他的健康状况持续恶化。",
    synonyms: ["worsen", "decline", "degrade"],
    antonyms: ["improve", "enhance", "ameliorate"],
    tags: ["CET6", "GRE"], difficulty: 4
  },
  {
    word: "diligent", phonetic: "/ˈdɪlɪdʒənt/", pos: "adj.",
    roots: "di-(分开) + lig(选择 choose) + ent → 精心挑选地做事 → 勤勉的",
    defEn: "having or showing care in one's work or duties",
    defZh: "勤奋的；勤勉的；用功的",
    mnemonic: "谐音'滴里根特' → 像滴水穿石一样根基特别扎实 → 勤奋",
    exampleEn: "She is a diligent student who always completes her work.",
    exampleZh: "她是个勤奋的学生，总是完成作业。",
    synonyms: ["industrious", "hardworking", "assiduous"],
    antonyms: ["lazy", "idle", "negligent"],
    tags: ["CET4"], difficulty: 2
  },
  {
    word: "eloquent", phonetic: "/ˈeləkwənt/", pos: "adj.",
    roots: "e-(出) + loqu(说 speak) + ent → 说出来的 → 雄辩的",
    defEn: "fluent or persuasive in speaking or writing",
    defZh: "雄辩的；有口才的；有说服力的",
    mnemonic: "e(出来)+loqu(说)+ent → 能说出来的 → 口才好的",
    exampleEn: "She gave an eloquent speech at the ceremony.",
    exampleZh: "她在典礼上发表了一篇雄辩的演讲。",
    synonyms: ["articulate", "fluent", "expressive"],
    antonyms: ["inarticulate", "tongue-tied"],
    tags: ["GRE", "TOEFL"], difficulty: 3
  },
  {
    word: "enhance", phonetic: "/ɪnˈhɑːns/", pos: "v.",
    roots: "en-(使) + hance(高 high) → 使变高 → 增强",
    defEn: "to intensify, increase, or improve the quality of",
    defZh: "增强；提高；改善",
    mnemonic: "en(进入)+hance(高) → 进入更高层次 → 提高增强",
    exampleEn: "Technology can enhance learning outcomes.",
    exampleZh: "技术可以提高学习成果。",
    synonyms: ["improve", "augment", "boost"],
    antonyms: ["diminish", "reduce", "weaken"],
    tags: ["CET4"], difficulty: 2
  },
  {
    word: "exaggerate", phonetic: "/ɪɡˈzædʒəreɪt/", pos: "v.",
    roots: "ex-(出/超出) + agger(堆积 heap) + ate → 堆积过多 → 夸大",
    defEn: "to represent as larger or greater than it really is",
    defZh: "夸张；夸大；言过其实",
    mnemonic: "ex(超出)+agger(堆积) → 超出地堆积 → 夸大",
    exampleEn: "Don't exaggerate the problem.",
    exampleZh: "不要夸大这个问题。",
    synonyms: ["overstate", "embellish", "amplify"],
    antonyms: ["understate", "minimize", "downplay"],
    tags: ["CET4"], difficulty: 2
  },
  {
    word: "fluctuate", phonetic: "/ˈflʌktʃueɪt/", pos: "v.",
    roots: "fluct(流动 flow) + u + ate → 像水一样流动 → 波动",
    defEn: "to rise and fall irregularly in number or amount",
    defZh: "波动；涨落；起伏不定",
    mnemonic: "fluct(像flux流动)+uate → 像水流一样上下浮动 → 波动",
    exampleEn: "Stock prices fluctuate daily.",
    exampleZh: "股票价格每天都在波动。",
    synonyms: ["vary", "oscillate", "swing"],
    antonyms: ["stabilize", "steady", "remain"],
    tags: ["CET6", "TOEFL"], difficulty: 3
  },
  {
    word: "inevitable", phonetic: "/ɪnˈevɪtəbl/", pos: "adj.",
    roots: "in-(不) + e(出) + vit(避免 avoid) + able → 不可避免的",
    defEn: "certain to happen; unavoidable",
    defZh: "不可避免的；必然的",
    mnemonic: "in(不)+evit(避免)+able(能) → 不能避免的 → 必然的",
    exampleEn: "Change is inevitable in life.",
    exampleZh: "生活中变化是不可避免的。",
    synonyms: ["unavoidable", "inescapable", "certain"],
    antonyms: ["avoidable", "uncertain", "preventable"],
    tags: ["CET4", "TOEFL"], difficulty: 3
  },
  {
    word: "meticulous", phonetic: "/məˈtɪkjələs/", pos: "adj.",
    roots: "met(恐惧 fear) + icul + ous → 因害怕出错而小心翼翼",
    defEn: "showing great attention to detail; very careful",
    defZh: "一丝不苟的；小心翼翼的；注重细节的",
    mnemonic: "met(遇到)+iculous → 遇到每件事都仔细对待 → 一丝不苟",
    exampleEn: "She kept meticulous records of every expense.",
    exampleZh: "她对每笔开支都做了详细记录。",
    synonyms: ["thorough", "precise", "painstaking"],
    antonyms: ["careless", "sloppy", "negligent"],
    tags: ["GRE", "TOEFL"], difficulty: 4
  },
  {
    word: "paradox", phonetic: "/ˈpærədɒks/", pos: "n.",
    roots: "para-(旁边/相反) + dox(观点 opinion) → 相反的观点 → 悖论",
    defEn: "a seemingly contradictory statement that may be true",
    defZh: "悖论；矛盾的人或事；似非而是的说法",
    mnemonic: "para(相反)+dox(观点) → 相反的观点竟然都对 → 悖论",
    exampleEn: "It's a paradox that the richest country has the most poverty.",
    exampleZh: "最富有的国家却有最多的贫困，这是个悖论。",
    synonyms: ["contradiction", "anomaly", "enigma"],
    antonyms: ["certainty", "truth"],
    tags: ["GRE", "TOEFL"], difficulty: 4
  },
  {
    word: "persevere", phonetic: "/ˌpɜːsɪˈvɪə/", pos: "v.",
    roots: "per-(完全/始终) + sever(严肃 severe/serious) + e → 始终严肃对待 → 坚持不懈",
    defEn: "to continue in a course of action despite difficulty",
    defZh: "坚持不懈；锲而不舍",
    mnemonic: "per(始终)+severe(严格) → 始终严格要求自己 → 坚持不懈",
    exampleEn: "You must persevere if you want to succeed.",
    exampleZh: "如果你想成功，就必须坚持不懈。",
    synonyms: ["persist", "endure", "continue"],
    antonyms: ["quit", "surrender", "abandon"],
    tags: ["CET6"], difficulty: 3
  },
  {
    word: "pragmatic", phonetic: "/præɡˈmætɪk/", pos: "adj.",
    roots: "pragma-(行动/事务 deed) + tic → 注重实际行动的",
    defEn: "dealing with things sensibly and realistically",
    defZh: "务实的；实用主义的；注重实效的",
    mnemonic: "prag(实践)+matic → 注重实践的 → 务实的",
    exampleEn: "We need a pragmatic approach to solve this problem.",
    exampleZh: "我们需要一种务实的方法来解决这个问题。",
    synonyms: ["practical", "realistic", "sensible"],
    antonyms: ["idealistic", "impractical", "theoretical"],
    tags: ["GRE", "TOEFL"], difficulty: 4
  },
  {
    word: "resilient", phonetic: "/rɪˈzɪliənt/", pos: "adj.",
    roots: "re-(回) + sil(跳 leap) + ient → 跳回来的 → 有弹性的/恢复力强的",
    defEn: "able to recover quickly from difficulties; tough",
    defZh: "有弹性的；能迅速恢复的；适应力强的",
    mnemonic: "re(回来)+sili(跳)+ent → 跳回来 → 弹性好/恢复力强",
    exampleEn: "Children are remarkably resilient.",
    exampleZh: "孩子们的适应力非常强。",
    synonyms: ["tough", "hardy", "adaptable"],
    antonyms: ["fragile", "vulnerable", "delicate"],
    tags: ["TOEFL", "GRE"], difficulty: 3
  },
  {
    word: "ubiquitous", phonetic: "/juːˈbɪkwɪtəs/", pos: "adj.",
    roots: "ubique(到处 everywhere) + ous → 到处都有的",
    defEn: "present, appearing, or found everywhere",
    defZh: "无处不在的；普遍存在的",
    mnemonic: "u(你)+bi(必)+quit(离开)+ous → 你必须离开也逃不掉 → 到处都是",
    exampleEn: "Smartphones have become ubiquitous in modern life.",
    exampleZh: "智能手机在现代生活中已经无处不在。",
    synonyms: ["omnipresent", "pervasive", "universal"],
    antonyms: ["rare", "scarce", "uncommon"],
    tags: ["GRE", "TOEFL"], difficulty: 5
  },
  {
    word: "advocate", phonetic: "/ˈædvəkeɪt/", pos: "v./n.",
    roots: "ad-(朝向) + voc(声音/叫 call) + ate → 为…发声",
    defEn: "to publicly support or recommend; a person who supports",
    defZh: "提倡；拥护；倡导者",
    mnemonic: "ad(朝向)+voc(声音)+ate → 朝着某个方向发出声音 → 倡导",
    exampleEn: "She advocates for equal rights.",
    exampleZh: "她倡导平等权利。",
    synonyms: ["support", "promote", "champion"],
    antonyms: ["oppose", "criticize", "discourage"],
    tags: ["CET6", "TOEFL"], difficulty: 3
  },
  {
    word: "ephemeral", phonetic: "/ɪˈfemərəl/", pos: "adj.",
    roots: "epi-(在…上) + hemer(天 day) + al → 只在一天之上的 → 短暂的",
    defEn: "lasting for a very short time",
    defZh: "短暂的；转瞬即逝的",
    mnemonic: "e+phemeral → 像飞沫(phemeral谐音)一样转瞬即逝",
    exampleEn: "Fame in the modern world is often ephemeral.",
    exampleZh: "现代世界的名声往往是短暂的。",
    synonyms: ["transient", "fleeting", "momentary"],
    antonyms: ["permanent", "enduring", "eternal"],
    tags: ["GRE"], difficulty: 5
  },
  {
    word: "gregarious", phonetic: "/ɡrɪˈɡeəriəs/", pos: "adj.",
    roots: "greg(群 flock/group) + arious → 喜欢群居的 → 爱社交的",
    defEn: "fond of company; sociable",
    defZh: "爱社交的；群居的；合群的",
    mnemonic: "greg(group群)+arious → 喜欢群体的 → 爱社交的",
    exampleEn: "He's a gregarious person who loves parties.",
    exampleZh: "他是一个爱社交的人，喜欢参加派对。",
    synonyms: ["sociable", "outgoing", "extroverted"],
    antonyms: ["introverted", "solitary", "antisocial"],
    tags: ["GRE"], difficulty: 5
  },
  {
    word: "scrutinize", phonetic: "/ˈskruːtɪnaɪz/", pos: "v.",
    roots: "scrut(检查 examine) + in + ize → 仔细检查",
    defEn: "to examine or inspect closely and thoroughly",
    defZh: "仔细检查；审查；细看",
    mnemonic: "scrut(仔细看)+in+ize → 仔细往里面看 → 审查",
    exampleEn: "Every detail of the plan was scrutinized.",
    exampleZh: "计划的每一个细节都被仔细审查。",
    synonyms: ["examine", "inspect", "analyze"],
    antonyms: ["overlook", "ignore", "glance"],
    tags: ["GRE", "TOEFL"], difficulty: 4
  }
];
